steps:

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute' , 'scp' , '.' , 'instance-3:/home/khushaboo_khudia']

timeout: 1200s
