steps:

- name: 'ubuntu'
  args: ['bash', '-c' , 'pwd']


- name: 'ubuntu'
  args: ['bash', '-c' , 'ls']
# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute' , 'scp' , '*' , 'khushaboo_khudia@instance-3:/home/khushaboo_khudia/demo' , '--recurse' , '--scp-flag=-r' , '--zone=us-central1-a']

timeout: 1200s
