steps:

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/$PROJECT_ID/gcloud'
  args: ['compute' , 'scp' , '.' , 'instance-3:']

timeout: 1200s