#! /bin/bash
apt-get update
apt-get install -y apache2
cat <<EOF > /var/www/html/index.html
<html><body><h1>Running Startup Scripts</h1>
<p>I was created in automated fashion using simple startup script!</p>
</body></html>
